# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2

from PyQt5 import QtCore, QtGui, QtWidgets
from time import sleep
from style_sheet_data import style_sheets
from gui_manual import inicio, sim_peso, motor, bascula, ajustes

from gui_functions import set_values, tab_change, round_int, close
from gui_functions import slider_sim_w, sim_w_loop, addsub_w, sim_num_input
from gui_functions import motor_vel, mot_hold_turn, mot_stop, mot_auto_turn
from gui_functions import cambiar_w_celula, sca_num_input, calibrar_cel, estimar_k
from gui_functions import settings_text, set_num_input, select_setting, settings_menu


class Ui_MainWindow(object):
    goal_w, sim_w_on = 500, False  # Sim Weight data
    mot_vel, mot_dir_fwd, mot_turning = None, None, False # Motor tab data
    mot_auto_fwd, mot_auto_bwd = False, False # Motor tab data
    calibration_step, calibration_info, scale_on = -1, {}, False  # Scale tab data
    selected_setting, set_buttons = None, None  # Settings data

    ui_data = {
        'k': None,
        'sim_slider_precision': None,
        'error': None,
        'min_mot_vel': None,
        'max_mot_vel': None,
        'mot_slider_divs': None,
        'w_cel_carga': None,
        'sca_n_measures': None,
        }
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 450)
        #MainWindow.setStyleSheet("")

        set_values(self)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{background-color:grey;}")
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet(style_sheets['tab_widget'])
        self.tabWidget.currentChanged.connect(lambda: tab_change(self))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        font = QtGui.QFont()
	
        ##### TAB SIM WEIGHT #####
        self.tab_sim_w = QtWidgets.QWidget()
        self.tab_sim_w.setObjectName("tab_sim_w")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_sim_w)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.sim_h_layout_1 = QtWidgets.QHBoxLayout()
        self.sim_h_layout_1.setObjectName("sim_h_layout_1")
        self.slider_sim_w = QtWidgets.QSlider(self.tab_sim_w)
        self.slider_sim_w.setSizePolicy(sizePolicy)
        self.slider_sim_w.setOrientation(QtCore.Qt.Horizontal)        
        self.slider_sim_w.setMaximum(2000)
        self.slider_sim_w.setValue(round_int(self.goal_w, self.ui_data['sim_slider_precision']))
        self.slider_sim_w.setObjectName("slider_sim_w")
        self.sim_h_layout_1.addWidget(self.slider_sim_w)
        self.lcd_sim_w = QtWidgets.QLCDNumber(self.tab_sim_w)
        self.lcd_sim_w.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lcd_sim_w.setDigitCount(4)
        self.lcd_sim_w.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_sim_w.setProperty("intValue", self.goal_w)
        self.lcd_sim_w.setObjectName("lcd_sim_w")
        self.sim_h_layout_1.addWidget(self.lcd_sim_w)
        self.g_label_sim1 = QtWidgets.QLabel(self.tab_sim_w)
        self.g_label_sim1.setObjectName("g_label_sim1")
        self.sim_h_layout_1.addWidget(self.g_label_sim1)
        self.verticalLayout_2.addLayout(self.sim_h_layout_1)

        self.sim_h_layout_2 = QtWidgets.QHBoxLayout()
        self.sim_h_layout_2.setObjectName("sim_h_layout_2")
        self.slider_real_w = QtWidgets.QSlider(self.tab_sim_w)
        self.slider_real_w.setSizePolicy(sizePolicy)
        self.slider_real_w.setStyleSheet("")
        self.slider_real_w.setOrientation(QtCore.Qt.Horizontal)
        self.slider_real_w.setMaximum(2000)
        self.slider_real_w.setValue(0)
        self.slider_real_w.setStyleSheet('QSlider::groove{background:grey}')
        self.slider_real_w.setEnabled(False)
        self.slider_real_w.setObjectName("slider_real_w")
        self.sim_h_layout_2.addWidget(self.slider_real_w)
        self.lcd_real_w = QtWidgets.QLCDNumber(self.tab_sim_w)
        self.lcd_real_w.setDigitCount(4)
        self.lcd_real_w.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_real_w.display('----')
        self.lcd_real_w.setObjectName("lcd_real_w")
        self.sim_h_layout_2.addWidget(self.lcd_real_w)
        self.g_label_sim2 = QtWidgets.QLabel(self.tab_sim_w)
        self.g_label_sim2.setObjectName("g_label_sim2")
        self.sim_h_layout_2.addWidget(self.g_label_sim2)
        self.verticalLayout_2.addLayout(self.sim_h_layout_2)

        self.sim_h_layout_3 = QtWidgets.QHBoxLayout()
        self.sim_h_layout_3.setObjectName("sim_h_layout_3")
        self.sim_addsub_gridlayout = QtWidgets.QGridLayout()
        self.sim_addsub_gridlayout.setObjectName("sim_addsub_gridlayout")

        self.b_m10 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_m10.setSizePolicy(sizePolicy)
        self.b_m10.setObjectName("b_m10")
        self.sim_addsub_gridlayout.addWidget(self.b_m10, 0, 0, 1, 1)
        self.b_m50 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_m50.setSizePolicy(sizePolicy)
        self.b_m50.setObjectName("b_m50")
        self.sim_addsub_gridlayout.addWidget(self.b_m50, 1, 0, 1, 1)
        self.b_m100 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_m100.setSizePolicy(sizePolicy)
        self.b_m100.setObjectName("b_m100")
        self.sim_addsub_gridlayout.addWidget(self.b_m100, 2, 0, 1, 1)
        self.b_m500 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_m500.setSizePolicy(sizePolicy)
        self.b_m500.setObjectName("b_m500")
        self.sim_addsub_gridlayout.addWidget(self.b_m500, 3, 0, 1, 1)
        self.b_m1000 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_m1000.setSizePolicy(sizePolicy)
        self.b_m1000.setObjectName("b_m1000")
        self.sim_addsub_gridlayout.addWidget(self.b_m1000, 4, 0, 1, 1)

        self.b_p10 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_p10.setSizePolicy(sizePolicy)
        self.b_p10.setObjectName("b_p10")
        self.sim_addsub_gridlayout.addWidget(self.b_p10, 0, 1, 1, 1)
        self.b_p50 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_p50.setSizePolicy(sizePolicy)
        self.b_p50.setObjectName("b_p50")
        self.sim_addsub_gridlayout.addWidget(self.b_p50, 1, 1, 1, 1)
        self.b_p100 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_p100.setSizePolicy(sizePolicy)
        self.b_p100.setObjectName("b_p100")
        self.sim_addsub_gridlayout.addWidget(self.b_p100, 2, 1, 1, 1)
        self.b_p500 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_p500.setSizePolicy(sizePolicy)
        self.b_p500.setObjectName("b_p500")
        self.sim_addsub_gridlayout.addWidget(self.b_p500, 3, 1, 1, 1)
        self.b_p1000 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_p1000.setSizePolicy(sizePolicy)
        self.b_p1000.setObjectName("b_p1000")
        self.sim_addsub_gridlayout.addWidget(self.b_p1000, 4, 1, 1, 1)

        self.sim_h_layout_3.addLayout(self.sim_addsub_gridlayout)
        self.sim_v_layout = QtWidgets.QVBoxLayout()
        self.sim_v_layout.setContentsMargins(-1, -1, 0, -1)
        self.sim_v_layout.setObjectName("sim_v_layout")
        self.frame_err = QtWidgets.QFrame(self.tab_sim_w)
        self.frame_err.setStyleSheet(style_sheets['frame_err'])
        self.frame_err.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_err.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_err.setObjectName("frame_err")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_err)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_err_adm = QtWidgets.QLabel(self.frame_err)
        self.label_err_adm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_err_adm.setObjectName("label_err_adm")
        self.gridLayout_4.addWidget(self.label_err_adm, 1, 0, 1, 1)
        self.lcd_err_adm = QtWidgets.QLCDNumber(self.frame_err)
        self.lcd_err_adm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcd_err_adm.setDigitCount(5)
        self.lcd_err_adm.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_err_adm.display(self.ui_data['error'])
        self.lcd_err_adm.setObjectName("lcd_err_adm")
        self.gridLayout_4.addWidget(self.lcd_err_adm, 1, 1, 1, 1)
        self.lcd_err_act = QtWidgets.QLCDNumber(self.frame_err)
        self.lcd_err_act.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_err_act.display('-----')
        self.lcd_err_act.setObjectName("lcd_err_act")
        self.gridLayout_4.addWidget(self.lcd_err_act, 0, 1, 1, 1)
        self.label_err_act = QtWidgets.QLabel(self.frame_err)
        self.label_err_act.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_err_act.setObjectName("label_err_act")
        self.gridLayout_4.addWidget(self.label_err_act, 0, 0, 1, 1)
        self.sim_v_layout.addWidget(self.frame_err)
        self.start_button = QtWidgets.QPushButton(self.tab_sim_w)
        sizePolicy1 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.start_button.setSizePolicy(sizePolicy1)
        self.start_button.setStyleSheet(style_sheets['start_button'])
        self.start_button.setObjectName("start_button")
        self.sim_v_layout.addWidget(self.start_button, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.sim_v_layout.setStretch(0, 1)
        self.sim_v_layout.setStretch(1, 2)
        self.sim_h_layout_3.addLayout(self.sim_v_layout)
        self.sim_num_input = QtWidgets.QVBoxLayout()
        self.sim_num_input.setObjectName("sim_num_input")
        self.label_sim_input = QtWidgets.QLabel(self.tab_sim_w)
        self.label_sim_input.setStyleSheet(style_sheets['label_num_input'])
        self.label_sim_input.setObjectName("label_sim_input")
        self.sim_num_input.addWidget(self.label_sim_input)
        self.label_sim_input.setAlignment(QtCore.Qt.AlignCenter)
        self.sim_num_buttons = QtWidgets.QGridLayout()
        self.sim_num_buttons.setObjectName("sim_num_buttons")

        self.b_sim1 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_sim1.setSizePolicy(sizePolicy)
        self.b_sim1.setObjectName("b_sim1")
        self.sim_num_buttons.addWidget(self.b_sim1, 0, 0, 1, 1)
        self.b_sim2 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_sim2.setSizePolicy(sizePolicy)
        self.b_sim2.setObjectName("b_sim2")
        self.sim_num_buttons.addWidget(self.b_sim2, 0, 1, 1, 1)
        self.b_sim3 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_sim3.setSizePolicy(sizePolicy)
        self.b_sim3.setObjectName("b_sim3")
        self.sim_num_buttons.addWidget(self.b_sim3, 0, 2, 1, 1)

        self.b_sim4 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_sim4.setSizePolicy(sizePolicy)
        self.b_sim4.setObjectName("b_sim4")
        self.sim_num_buttons.addWidget(self.b_sim4, 1, 0, 1, 1)
        self.b_sim5 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_sim5.setSizePolicy(sizePolicy)
        self.b_sim5.setObjectName("b_sim5")
        self.sim_num_buttons.addWidget(self.b_sim5, 1, 1, 1, 1)
        self.b_sim6 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_sim6.setSizePolicy(sizePolicy)
        self.b_sim6.setObjectName("b_sim6")
        self.sim_num_buttons.addWidget(self.b_sim6, 1, 2, 1, 1)
        
        self.b_sim7 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_sim7.setSizePolicy(sizePolicy)
        self.b_sim7.setObjectName("b_sim7")
        self.sim_num_buttons.addWidget(self.b_sim7, 2, 0, 1, 1)
        self.b_sim8 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_sim8.setSizePolicy(sizePolicy)
        self.b_sim8.setObjectName("b_sim8")
        self.sim_num_buttons.addWidget(self.b_sim8, 2, 1, 1, 1)
        self.b_sim9 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_sim9.setSizePolicy(sizePolicy)
        self.b_sim9.setObjectName("b_sim9")
        self.sim_num_buttons.addWidget(self.b_sim9, 2, 2, 1, 1)
         
        self.b_sim_del = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_sim_del.setSizePolicy(sizePolicy)
        self.b_sim_del.setObjectName("b_sim_del")
        self.sim_num_buttons.addWidget(self.b_sim_del, 3, 0, 1, 1)
        self.b_sim0 = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_sim0.setSizePolicy(sizePolicy)
        self.b_sim0.setObjectName("b_sim0")
        self.sim_num_buttons.addWidget(self.b_sim0, 3, 1, 1, 1)
        self.b_sim_enter = QtWidgets.QPushButton(self.tab_sim_w)
        self.b_sim_enter.setSizePolicy(sizePolicy)
        self.b_sim_enter.setObjectName("b_sim_enter")
        self.sim_num_buttons.addWidget(self.b_sim_enter, 3, 2, 1, 1)
        
        self.sim_num_input.addLayout(self.sim_num_buttons)
        self.sim_num_input.setStretch(0, 1)
        self.sim_num_input.setStretch(1, 3)
        self.sim_h_layout_3.addLayout(self.sim_num_input)
        self.sim_h_layout_3.setStretch(0, 1)
        self.sim_h_layout_3.setStretch(1, 1)
        self.sim_h_layout_3.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.sim_h_layout_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 4)

        self.tabWidget.addTab(self.tab_sim_w, "")

        ## TAB SIM WEIGHT FUNCTIONS ##

        self.slider_sim_w.sliderMoved.connect(lambda: slider_sim_w(self))
        self.start_button.clicked.connect(lambda: sim_w_loop(self))

        self.b_m10.clicked.connect(lambda: addsub_w(self, -10))
        self.b_m50.clicked.connect(lambda: addsub_w(self, -50))
        self.b_m100.clicked.connect(lambda: addsub_w(self, -100))
        self.b_m500.clicked.connect(lambda: addsub_w(self, -500))
        self.b_m1000.clicked.connect(lambda: addsub_w(self, -1000))
        self.b_p10.clicked.connect(lambda: addsub_w(self, 10))
        self.b_p50.clicked.connect(lambda: addsub_w(self, 50))
        self.b_p100.clicked.connect(lambda: addsub_w(self, 100))
        self.b_p500.clicked.connect(lambda: addsub_w(self, 500))
        self.b_p1000.clicked.connect(lambda: addsub_w(self, 1000))

        self.b_sim0.clicked.connect(lambda: sim_num_input(self, 0))
        self.b_sim1.clicked.connect(lambda: sim_num_input(self, 1))
        self.b_sim2.clicked.connect(lambda: sim_num_input(self, 2))
        self.b_sim3.clicked.connect(lambda: sim_num_input(self, 3))
        self.b_sim4.clicked.connect(lambda: sim_num_input(self, 4))
        self.b_sim5.clicked.connect(lambda: sim_num_input(self, 5))
        self.b_sim6.clicked.connect(lambda: sim_num_input(self, 6))
        self.b_sim7.clicked.connect(lambda: sim_num_input(self, 7))
        self.b_sim8.clicked.connect(lambda: sim_num_input(self, 8))
        self.b_sim9.clicked.connect(lambda: sim_num_input(self, 9))
        self.b_sim_del.clicked.connect(lambda: sim_num_input(self, 11))
        self.b_sim_enter.clicked.connect(lambda: sim_num_input(self, 12))
        
        
        ##### TAB MOTOR #####
        
        self.tab_motor = QtWidgets.QWidget()
        self.tab_motor.setObjectName("tab_motor")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_motor)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_mot = QtWidgets.QFrame(self.tab_motor)
        self.frame_mot.setStyleSheet(style_sheets['frame_mot'])
        self.frame_mot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_mot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_mot.setObjectName("frame_mot")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_mot)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")

        self.mot_des_vlayout = QtWidgets.QVBoxLayout()
        self.mot_des_vlayout.setContentsMargins(-1, -1, 0, -1)
        self.mot_des_vlayout.setObjectName("mot_des_vlayout")
        self.b_des_hold = QtWidgets.QPushButton(self.frame_mot)
        sizePolicy1 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.b_des_hold.setSizePolicy(sizePolicy1)
        self.b_des_hold.setMinimumSize(QtCore.QSize(0, 100))
        self.b_des_hold.setObjectName("b_des_hold")
        self.mot_des_vlayout.addWidget(self.b_des_hold)
        self.b_des_auto = QtWidgets.QPushButton(self.frame_mot)
        self.b_des_auto.setObjectName("b_des_auto")
        self.mot_des_vlayout.addWidget(self.b_des_auto)
        self.horizontalLayout_14.addLayout(self.mot_des_vlayout)

        self.mot_info_vlayout = QtWidgets.QVBoxLayout()
        self.mot_info_vlayout.setContentsMargins(10, 10, 10, 10)
        self.mot_info_vlayout.setObjectName("mot_info_vlayout")
        self.mot_hlayout = QtWidgets.QHBoxLayout()
        self.mot_hlayout.setContentsMargins(-1, -1, -1, 0)
        self.mot_hlayout.setObjectName("mot_hlayout")
        self.mot_hlayout.addItem(spacerItem)
        self.lcd_mot_w = QtWidgets.QLCDNumber(self.frame_mot)
        sizePolicy1 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.lcd_mot_w.setSizePolicy(sizePolicy1)
        self.lcd_mot_w.setSmallDecimalPoint(True)
        self.lcd_mot_w.setDigitCount(4)
        self.lcd_mot_w.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_mot_w.setObjectName("lcd_mot_w")
        self.mot_hlayout.addWidget(self.lcd_mot_w)
        self.g_label_mot = QtWidgets.QLabel(self.frame_mot)
        sizePolicy1 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.g_label_mot.setSizePolicy(sizePolicy1)
        font.setPointSize(15)
        self.g_label_mot.setFont(font)
        self.g_label_mot.setObjectName("g_label_mot")
        self.mot_hlayout.addWidget(self.g_label_mot)
        self.mot_hlayout.addItem(spacerItem)
        self.mot_hlayout.setStretch(1, 1)
        self.mot_info_vlayout.addLayout(self.mot_hlayout)
        self.slider_mot_vel = QtWidgets.QSlider(self.frame_mot)
        self.slider_mot_vel.setSizePolicy(sizePolicy)
        self.slider_mot_vel.setStyleSheet("")
        self.slider_mot_vel.setMaximum(self.ui_data['mot_slider_divs']-1)
        self.slider_mot_vel.setValue(int(self.ui_data['mot_slider_divs']/2))
        self.slider_mot_vel.setOrientation(QtCore.Qt.Vertical)
        self.slider_mot_vel.setObjectName("slider_mot_vel")
        self.mot_info_vlayout.addWidget(self.slider_mot_vel)
        self.label_mot_vel = QtWidgets.QLabel(self.frame_mot)
        self.label_mot_vel.setSizePolicy(sizePolicy)
        self.label_mot_vel.setStyleSheet('QLabel{font:bold 15px}')
        self.label_mot_vel.setAlignment(QtCore.Qt.AlignCenter)
        motor_vel(self)
        self.label_mot_vel.setObjectName("label_mot_vel")
        self.mot_info_vlayout.addWidget(self.label_mot_vel, 0, QtCore.Qt.AlignHCenter)
        self.mot_info_vlayout.setStretch(0, 3)
        self.mot_info_vlayout.setStretch(1, 20)
        self.mot_info_vlayout.setStretch(2, 1)
        self.horizontalLayout_14.addLayout(self.mot_info_vlayout)

        self.mot_enr_vlayout = QtWidgets.QVBoxLayout()
        self.mot_enr_vlayout.setContentsMargins(-1, -1, 0, -1)
        self.mot_enr_vlayout.setObjectName("mot_enr_vlayout")
        self.b_enr_hold = QtWidgets.QPushButton(self.frame_mot)
        sizePolicy1 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.b_enr_hold.setSizePolicy(sizePolicy1)
        self.b_enr_hold.setMinimumSize(QtCore.QSize(0, 100))
        self.b_enr_hold.setObjectName("b_enr_hold")
        self.mot_enr_vlayout.addWidget(self.b_enr_hold)
        self.b_enr_auto = QtWidgets.QPushButton(self.frame_mot)
        self.b_enr_auto.setObjectName("b_enr_auto")
        self.mot_enr_vlayout.addWidget(self.b_enr_auto)
        self.horizontalLayout_14.addLayout(self.mot_enr_vlayout)
        self.horizontalLayout_2.addWidget(self.frame_mot)
        self.tabWidget.addTab(self.tab_motor, "")

        ## TAB MOTOR FUNCTIONS ##

        self.slider_mot_vel.valueChanged.connect(lambda: motor_vel(self))

        self.b_enr_hold.pressed.connect(lambda: mot_hold_turn(self, True))
        self.b_des_hold.pressed.connect(lambda: mot_hold_turn(self, False))
        self.b_enr_hold.released.connect(lambda: mot_stop(self))
        self.b_des_hold.released.connect(lambda: mot_stop(self))

        self.b_enr_auto.clicked.connect(lambda: mot_auto_turn(self, True))
        self.b_des_auto.clicked.connect(lambda: mot_auto_turn(self, False))



        ##### TAB SCALE #####
        self.tab_scale = QtWidgets.QWidget()
        self.tab_scale.setObjectName("tab_scale")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_scale)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.sca_h_layout1 = QtWidgets.QHBoxLayout()
        self.sca_h_layout1.setContentsMargins(10, 0, 10, 0)
        self.sca_h_layout1.setSpacing(10)
        self.sca_h_layout1.setObjectName("sca_h_layout1")
        self.sca_h_layout1.addItem(spacerItem)
        self.sca_h_layout2 = QtWidgets.QHBoxLayout()
        self.sca_h_layout2.setContentsMargins(-1, -1, 0, -1)
        self.sca_h_layout2.setObjectName("sca_h_layout2")
        self.lcd_sca_w = QtWidgets.QLCDNumber(self.tab_scale)
        self.lcd_sca_w.setSizePolicy(sizePolicy)
        self.lcd_sca_w.setDigitCount(4)
        self.lcd_sca_w.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_sca_w.display("----")
        self.lcd_sca_w.setObjectName("lcd_sca_w")
        self.sca_h_layout2.addWidget(self.lcd_sca_w)
        self.g_label_sca = QtWidgets.QLabel(self.tab_scale)
        sizePolicy1 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.g_label_sca.setSizePolicy(sizePolicy1)
        font.setPointSize(20)
        self.g_label_sca.setFont(font)
        self.g_label_sca.setObjectName("g_label_sca")
        self.sca_h_layout2.addWidget(self.g_label_sca)
        self.sca_h_layout1.addLayout(self.sca_h_layout2)
        self.sca_h_layout1.addItem(spacerItem)
        self.sca_h_layout1.setStretch(0, 1)
        self.sca_h_layout1.setStretch(1, 1)
        self.sca_h_layout1.setStretch(2, 1)
        self.verticalLayout_7.addLayout(self.sca_h_layout1)

        self.sca_h_layout3 = QtWidgets.QHBoxLayout()
        self.sca_h_layout3.setObjectName("sca_h_layout3")
        self.sca_v_layout1 = QtWidgets.QVBoxLayout()
        self.sca_v_layout1.setContentsMargins(-1, -1, 0, -1)
        self.sca_v_layout1.setObjectName("sca_v_layout1")
        self.frame_sca_cel_w = QtWidgets.QFrame(self.tab_scale)
        self.frame_sca_cel_w.setStyleSheet(style_sheets['frame_sca_cel_w'])
        self.frame_sca_cel_w.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sca_cel_w.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sca_cel_w.setObjectName("frame_sca_cel_w")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_sca_cel_w)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_sca_cel_w = QtWidgets.QLabel(self.frame_sca_cel_w)
        self.label_sca_cel_w.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sca_cel_w.setObjectName("label_sca_cel_w")
        self.horizontalLayout_18.addWidget(self.label_sca_cel_w)
        self.lcd_sca_cel_w = QtWidgets.QLCDNumber(self.frame_sca_cel_w)
        self.lcd_sca_cel_w.setSizePolicy(sizePolicy)
        self.lcd_sca_cel_w.setDigitCount(3)
        self.lcd_sca_cel_w.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_sca_cel_w.setObjectName("lcd_sca_cel_w")
        self.horizontalLayout_18.addWidget(self.lcd_sca_cel_w)
        #self.horizontalLayout_18.addItem(spacerItem)
        self.label_sca_colg_w = QtWidgets.QLabel(self.frame_sca_cel_w)
        self.label_sca_colg_w.setObjectName("label_sca_colg_w")
        self.horizontalLayout_18.addWidget(self.label_sca_colg_w)
        self.lcd_sca_colg_w = QtWidgets.QLCDNumber(self.frame_sca_cel_w)
        self.lcd_sca_colg_w.setDigitCount(4)
        self.lcd_sca_colg_w.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_sca_colg_w.setObjectName("lcd_sca_colg_w")
        self.horizontalLayout_18.addWidget(self.lcd_sca_colg_w)
        self.sca_v_layout1.addWidget(self.frame_sca_cel_w)

        self.frame_sca_b_cal = QtWidgets.QFrame(self.tab_scale)
        self.frame_sca_b_cal.setStyleSheet(style_sheets['frame_blue_buttons'])
        self.frame_sca_b_cal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sca_b_cal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sca_b_cal.setObjectName("frame_sca_b_cal")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_sca_b_cal)
        self.horizontalLayout_8.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.b_sca_cal = QtWidgets.QPushButton(self.frame_sca_b_cal)
        self.b_sca_cal.setSizePolicy(sizePolicy)
        self.b_sca_cal.setStyleSheet("")
        self.b_sca_cal.setObjectName("b_sca_cal")
        self.horizontalLayout_8.addWidget(self.b_sca_cal)
        self.b_sca_cel_w = QtWidgets.QPushButton(self.frame_sca_b_cal)
        self.b_sca_cel_w.setSizePolicy(sizePolicy)
        self.b_sca_cel_w.setStyleSheet("")
        self.b_sca_cel_w.setObjectName("b_sca_cel_w")
        self.horizontalLayout_8.addWidget(self.b_sca_cel_w)
        self.b_sca_k = QtWidgets.QPushButton(self.frame_sca_b_cal)
        self.b_sca_k.setSizePolicy(sizePolicy)
        self.b_sca_k.setObjectName("b_sca_k")
        self.horizontalLayout_8.addWidget(self.b_sca_k)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_8.setStretch(2, 1)
        self.sca_v_layout1.addWidget(self.frame_sca_b_cal)

        self.sca_grid_layout1 = QtWidgets.QGridLayout()
        self.sca_grid_layout1.setContentsMargins(-1, -1, -1, 0)
        self.sca_grid_layout1.setObjectName("sca_grid_layout1")
        self.b_sca_canc = QtWidgets.QPushButton(self.tab_scale)
        self.b_sca_canc.setSizePolicy(sizePolicy)
        self.b_sca_canc.setStyleSheet(style_sheets['red_button'])
        self.b_sca_canc.setObjectName("b_sca_canc")
        self.sca_grid_layout1.addWidget(self.b_sca_canc, 1, 1, 1, 1)
        self.b_sca_acep = QtWidgets.QPushButton(self.tab_scale)
        self.b_sca_acep.setSizePolicy(sizePolicy)
        self.b_sca_acep.setStyleSheet(style_sheets['green_button'])
        self.b_sca_acep.setObjectName("b_sca_acep")
        self.sca_grid_layout1.addWidget(self.b_sca_acep, 0, 1, 1, 1)
        self.label_sca_inst = QtWidgets.QLabel(self.tab_scale)
        self.label_sca_inst.setSizePolicy(sizePolicy)
        self.label_sca_inst.setStyleSheet(style_sheets['label_sca_inst'])
        self.label_sca_inst.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sca_inst.setObjectName("label_sca_inst")
        self.sca_grid_layout1.addWidget(self.label_sca_inst, 0, 0, 2, 1)
        self.sca_grid_layout1.setColumnStretch(0, 4)
        self.sca_grid_layout1.setColumnStretch(1, 1)
        self.sca_v_layout1.addLayout(self.sca_grid_layout1)
        self.sca_v_layout1.setStretch(0, 1)
        self.sca_v_layout1.setStretch(1, 3)
        self.sca_v_layout1.setStretch(2, 3)
        self.sca_h_layout3.addLayout(self.sca_v_layout1)
        
        self.sca_num_input = QtWidgets.QVBoxLayout()
        self.sca_num_input.setObjectName("sca_num_input")
        self.label_sca_input = QtWidgets.QLabel(self.tab_scale)
        self.label_sca_input.setObjectName("label_sca_input")
        self.label_sca_input.setStyleSheet(style_sheets['label_num_input'])
        self.label_sca_input.setAlignment(QtCore.Qt.AlignCenter)
        self.sca_num_input.addWidget(self.label_sca_input)
        self.sca_num_buttons = QtWidgets.QGridLayout()
        self.sca_num_buttons.setObjectName("sca_num_buttons")

        self.b_sca1 = QtWidgets.QPushButton(self.tab_scale)
        self.b_sca1.setSizePolicy(sizePolicy)
        self.b_sca1.setObjectName("b_sca1")
        self.sca_num_buttons.addWidget(self.b_sca1, 0, 0, 1, 1)
        self.b_sca2 = QtWidgets.QPushButton(self.tab_scale)
        self.b_sca2.setSizePolicy(sizePolicy)
        self.b_sca2.setObjectName("b_sca2")
        self.sca_num_buttons.addWidget(self.b_sca2, 0, 1, 1, 1)
        self.b_sca3 = QtWidgets.QPushButton(self.tab_scale)
        self.b_sca3.setSizePolicy(sizePolicy)
        self.b_sca3.setObjectName("b_sca3")
        self.sca_num_buttons.addWidget(self.b_sca3, 0, 2, 1, 1)

        self.b_sca4 = QtWidgets.QPushButton(self.tab_scale)
        self.b_sca4.setSizePolicy(sizePolicy)
        self.b_sca4.setObjectName("b_sca4")
        self.sca_num_buttons.addWidget(self.b_sca4, 1, 0, 1, 1)
        self.b_sca5 = QtWidgets.QPushButton(self.tab_scale)
        self.b_sca5.setSizePolicy(sizePolicy)
        self.b_sca5.setObjectName("b_sca5")
        self.sca_num_buttons.addWidget(self.b_sca5, 1, 1, 1, 1)
        self.b_sca6 = QtWidgets.QPushButton(self.tab_scale)
        self.b_sca6.setSizePolicy(sizePolicy)
        self.b_sca6.setObjectName("b_sca6")
        self.sca_num_buttons.addWidget(self.b_sca6, 1, 2, 1, 1)

        self.b_sca7 = QtWidgets.QPushButton(self.tab_scale)
        self.b_sca7.setSizePolicy(sizePolicy)
        self.b_sca7.setObjectName("b_sca7")
        self.sca_num_buttons.addWidget(self.b_sca7, 2, 0, 1, 1)
        self.b_sca8 = QtWidgets.QPushButton(self.tab_scale)
        self.b_sca8.setSizePolicy(sizePolicy)
        self.b_sca8.setObjectName("b_sca8")
        self.sca_num_buttons.addWidget(self.b_sca8, 2, 1, 1, 1)
        self.b_sca9 = QtWidgets.QPushButton(self.tab_scale)
        self.b_sca9.setSizePolicy(sizePolicy)
        self.b_sca9.setObjectName("b_sca9")
        self.sca_num_buttons.addWidget(self.b_sca9, 2, 2, 1, 1)
        
        self.b_sca_del = QtWidgets.QPushButton(self.tab_scale)
        self.b_sca_del.setSizePolicy(sizePolicy)
        self.b_sca_del.setObjectName("b_sca_del")
        self.sca_num_buttons.addWidget(self.b_sca_del, 3, 0, 1, 1)
        self.b_sca0 = QtWidgets.QPushButton(self.tab_scale)
        self.b_sca0.setSizePolicy(sizePolicy)
        self.b_sca0.setObjectName("b_sca0")
        self.sca_num_buttons.addWidget(self.b_sca0, 3, 1, 1, 1)
        self.b_sca_enter = QtWidgets.QPushButton(self.tab_scale)
        self.b_sca_enter.setSizePolicy(sizePolicy)
        self.b_sca_enter.setObjectName("b_sca_enter")
        self.sca_num_buttons.addWidget(self.b_sca_enter, 3, 2, 1, 1)

        self.sca_num_input.addLayout(self.sca_num_buttons)
        self.sca_num_input.setStretch(0, 1)
        self.sca_num_input.setStretch(1, 3)
        self.sca_h_layout3.addLayout(self.sca_num_input)
        self.sca_h_layout3.setStretch(0, 2)
        self.sca_h_layout3.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.sca_h_layout3)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 4)
        self.tabWidget.addTab(self.tab_scale, "")

        ## TAB SCALE FUNCTIONS ##

        self.b_sca_cel_w.clicked.connect(lambda: cambiar_w_celula(self))
        self.b_sca_k.clicked.connect(lambda: estimar_k(self))

        self.b_sca_cal.clicked.connect(lambda: calibrar_cel(self, 1))
        self.b_sca_acep.clicked.connect(lambda: calibrar_cel(self, self.calibration_step+1))
        self.b_sca_canc.clicked.connect(lambda: calibrar_cel(self, -1))

        self.b_sca0.clicked.connect(lambda: sca_num_input(self, 0))
        self.b_sca1.clicked.connect(lambda: sca_num_input(self, 1))
        self.b_sca2.clicked.connect(lambda: sca_num_input(self, 2))
        self.b_sca3.clicked.connect(lambda: sca_num_input(self, 3))
        self.b_sca4.clicked.connect(lambda: sca_num_input(self, 4))
        self.b_sca5.clicked.connect(lambda: sca_num_input(self, 5))
        self.b_sca6.clicked.connect(lambda: sca_num_input(self, 6))
        self.b_sca7.clicked.connect(lambda: sca_num_input(self, 7))
        self.b_sca8.clicked.connect(lambda: sca_num_input(self, 8))
        self.b_sca9.clicked.connect(lambda: sca_num_input(self, 9))
        self.b_sca_del.clicked.connect(lambda: sca_num_input(self, 11))
        self.b_sca_enter.clicked.connect(lambda: sca_num_input(self, 12))


        ##### TAB SETTINGS #####
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_settings)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.set_h_layout1 = QtWidgets.QHBoxLayout()
        self.set_h_layout1.setContentsMargins(-1, -1, 0, -1)
        self.set_h_layout1.setObjectName("set_h_layout1")

        self.set_scrollArea = QtWidgets.QScrollArea(self.tab_settings)
        self.set_scrollArea.setStyleSheet(style_sheets['scroll_bar'])
        self.set_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.set_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.set_scrollArea.setWidgetResizable(True)
        
        QtWidgets.QScroller.grabGesture(self.set_scrollArea, QtWidgets.QScroller.LeftMouseButtonGesture)
        self.set_scrollArea.setObjectName("set_scrollArea")
        self.set_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.set_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 391, 352))
        self.set_scrollAreaWidgetContents.setObjectName("set_scrollAreaWidgetContents")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.set_scrollAreaWidgetContents)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        
        self.radioButton_0 = QtWidgets.QRadioButton(self.set_scrollAreaWidgetContents)
        self.radioButton_0.setObjectName("radioButton_0")
        self.verticalLayout_10.addWidget(self.radioButton_0)
        self.radioButton_1 = QtWidgets.QRadioButton(self.set_scrollAreaWidgetContents)
        self.radioButton_1.setObjectName("radioButton_1")
        self.verticalLayout_10.addWidget(self.radioButton_1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.set_scrollAreaWidgetContents)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_10.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.set_scrollAreaWidgetContents)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_10.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.set_scrollAreaWidgetContents)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_10.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.set_scrollAreaWidgetContents)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_10.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.set_scrollAreaWidgetContents)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_10.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.set_scrollAreaWidgetContents)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_10.addWidget(self.radioButton_7)

        self.set_buttons = [self.radioButton_0, self.radioButton_1, self.radioButton_2,
                            self.radioButton_3, self.radioButton_4, self.radioButton_5,
                            self.radioButton_6, self.radioButton_7]
        
        settings_text(self)

        self.set_scrollArea.setWidget(self.set_scrollAreaWidgetContents)
        self.set_h_layout1.addWidget(self.set_scrollArea)
        self.set_num_input = QtWidgets.QVBoxLayout()
        self.set_num_input.setObjectName("set_num_input")
        self.label_set_input = QtWidgets.QLabel(self.tab_settings)
        self.label_set_input.setObjectName("label_set_input")
        self.set_num_input.addWidget(self.label_set_input)
        self.label_set_input.setStyleSheet(style_sheets['label_num_input'])
        self.label_set_input.setAlignment(QtCore.Qt.AlignCenter)

        self.set_num_buttons = QtWidgets.QGridLayout()
        self.set_num_buttons.setObjectName("set_num_buttons")

        self.b_set1 = QtWidgets.QPushButton(self.tab_settings)
        self.b_set1.setSizePolicy(sizePolicy)
        self.b_set1.setObjectName("b_set1")
        self.set_num_buttons.addWidget(self.b_set1, 0, 0, 1, 1)
        self.b_set2 = QtWidgets.QPushButton(self.tab_settings)
        self.b_set2.setSizePolicy(sizePolicy)
        self.b_set2.setObjectName("b_set2")
        self.set_num_buttons.addWidget(self.b_set2, 0, 1, 1, 1)
        self.b_set3 = QtWidgets.QPushButton(self.tab_settings)
        self.b_set3.setSizePolicy(sizePolicy)
        self.b_set3.setObjectName("b_set3")
        self.set_num_buttons.addWidget(self.b_set3, 0, 2, 1, 1)

        self.b_set4 = QtWidgets.QPushButton(self.tab_settings)
        self.b_set4.setSizePolicy(sizePolicy)
        self.b_set4.setObjectName("b_set4")
        self.set_num_buttons.addWidget(self.b_set4, 1, 0, 1, 1)
        self.b_set5 = QtWidgets.QPushButton(self.tab_settings)
        self.b_set5.setSizePolicy(sizePolicy)
        self.b_set5.setObjectName("b_set5")
        self.set_num_buttons.addWidget(self.b_set5, 1, 1, 1, 1)
        self.b_set6 = QtWidgets.QPushButton(self.tab_settings)
        self.b_set6.setSizePolicy(sizePolicy)
        self.b_set6.setObjectName("b_set6")
        self.set_num_buttons.addWidget(self.b_set6, 1, 2, 1, 1)

        self.b_set7 = QtWidgets.QPushButton(self.tab_settings)
        self.b_set7.setSizePolicy(sizePolicy)
        self.b_set7.setObjectName("b_set7")
        self.set_num_buttons.addWidget(self.b_set7, 2, 0, 1, 1)
        self.b_set8 = QtWidgets.QPushButton(self.tab_settings)
        self.b_set8.setSizePolicy(sizePolicy)
        self.b_set8.setObjectName("b_set8")
        self.set_num_buttons.addWidget(self.b_set8, 2, 1, 1, 1)
        self.b_set9 = QtWidgets.QPushButton(self.tab_settings)
        self.b_set9.setSizePolicy(sizePolicy)
        self.b_set9.setObjectName("b_set9")
        self.set_num_buttons.addWidget(self.b_set9, 2, 2, 1, 1)
        
        self.b_set_del = QtWidgets.QPushButton(self.tab_settings)
        self.b_set_del.setSizePolicy(sizePolicy)
        self.b_set_del.setObjectName("b_set_del")
        self.set_num_buttons.addWidget(self.b_set_del, 3, 0, 1, 1)
        self.b_set0 = QtWidgets.QPushButton(self.tab_settings)
        self.b_set0.setSizePolicy(sizePolicy)
        self.b_set0.setObjectName("b_set0")
        self.set_num_buttons.addWidget(self.b_set0, 3, 1, 1, 1)
        self.b_set_enter = QtWidgets.QPushButton(self.tab_settings)
        self.b_set_enter.setSizePolicy(sizePolicy)
        self.b_set_enter.setObjectName("b_set_enter")
        self.set_num_buttons.addWidget(self.b_set_enter, 3, 2, 1, 1)
        
        self.set_num_input.addLayout(self.set_num_buttons)
        self.set_num_input.setStretch(0, 1)
        self.set_num_input.setStretch(1, 6)
        self.set_h_layout1.addLayout(self.set_num_input)
        self.set_h_layout1.setStretch(0, 3)
        self.set_h_layout1.setStretch(1, 2)
        self.verticalLayout_9.addLayout(self.set_h_layout1)

        self.frame_set_buttons = QtWidgets.QFrame(self.tab_settings)
        self.frame_set_buttons.setStyleSheet(style_sheets['frame_blue_buttons'])
        self.frame_set_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_set_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_set_buttons.setObjectName("frame_set_buttons")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_set_buttons)
        self.horizontalLayout_16.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout_16.setSpacing(10)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.b_set_save = QtWidgets.QPushButton(self.frame_set_buttons)
        self.b_set_save.setSizePolicy(sizePolicy)
        self.b_set_save.setStyleSheet(style_sheets['green_button'])
        self.b_set_save.setObjectName("b_set_save")
        self.horizontalLayout_16.addWidget(self.b_set_save)
        self.b_set_apply = QtWidgets.QPushButton(self.frame_set_buttons)
        self.b_set_apply.setSizePolicy(sizePolicy)
        self.b_set_apply.setStyleSheet(style_sheets['yellow_button'])
        self.b_set_apply.setObjectName("b_set_apply")
        self.horizontalLayout_16.addWidget(self.b_set_apply)
        self.b_set_reset = QtWidgets.QPushButton(self.frame_set_buttons)
        self.b_set_reset.setSizePolicy(sizePolicy)
        self.b_set_reset.setObjectName("b_set_reset")
        self.horizontalLayout_16.addWidget(self.b_set_reset)
        self.b_set_undo = QtWidgets.QPushButton(self.frame_set_buttons)
        self.b_set_undo.setSizePolicy(sizePolicy)
        self.b_set_undo.setStyleSheet(style_sheets['red_button'])
        self.b_set_undo.setObjectName("b_set_undo")
        self.horizontalLayout_16.addWidget(self.b_set_undo)
        self.verticalLayout_9.addWidget(self.frame_set_buttons)
        self.verticalLayout_9.setStretch(0, 2)
        self.verticalLayout_9.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_settings, "")

        ## TAB SETTINGS FUNCTIONS ##

        self.b_set0.clicked.connect(lambda: set_num_input(self, 0))
        self.b_set1.clicked.connect(lambda: set_num_input(self, 1))
        self.b_set2.clicked.connect(lambda: set_num_input(self, 2))
        self.b_set3.clicked.connect(lambda: set_num_input(self, 3))
        self.b_set4.clicked.connect(lambda: set_num_input(self, 4))
        self.b_set5.clicked.connect(lambda: set_num_input(self, 5))
        self.b_set6.clicked.connect(lambda: set_num_input(self, 6))
        self.b_set7.clicked.connect(lambda: set_num_input(self, 7))
        self.b_set8.clicked.connect(lambda: set_num_input(self, 8))
        self.b_set9.clicked.connect(lambda: set_num_input(self, 9))
        self.b_set_del.clicked.connect(lambda: set_num_input(self, 11))
        self.b_set_enter.clicked.connect(lambda: set_num_input(self, 12))

        self.radioButton_0.clicked.connect(lambda: select_setting(self, 0))
        self.radioButton_1.clicked.connect(lambda: select_setting(self, 1))
        self.radioButton_2.clicked.connect(lambda: select_setting(self, 2))
        self.radioButton_3.clicked.connect(lambda: select_setting(self, 3))
        self.radioButton_4.clicked.connect(lambda: select_setting(self, 4))
        self.radioButton_5.clicked.connect(lambda: select_setting(self, 5))
        self.radioButton_6.clicked.connect(lambda: select_setting(self, 6))
        self.radioButton_7.clicked.connect(lambda: select_setting(self, 7))

        self.b_set_save.clicked.connect(lambda: settings_menu(self, 1))
        self.b_set_apply.clicked.connect(lambda: settings_menu(self, 2))
        self.b_set_reset.clicked.connect(lambda: settings_menu(self, 3))
        self.b_set_undo.clicked.connect(lambda: settings_menu(self, 4))

        ##### TAB HELP #####
        self.tab_help = QtWidgets.QWidget()
        self.tab_help.setObjectName("tab_help")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_help)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.help_toolBox = QtWidgets.QToolBox(self.tab_help)
        self.help_toolBox.setObjectName("help_toolBox")
        self.h_start = QtWidgets.QWidget()
        self.h_start.setGeometry(QtCore.QRect(0, 0, 747, 277))
        self.h_start.setObjectName("h_start")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.h_start)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.logos_h_layout = QtWidgets.QHBoxLayout()
        self.logos_h_layout.setObjectName("logos_h_layout")
        self.label_logo_upm = QtWidgets.QLabel(self.h_start)
        self.label_logo_upm.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo_upm.setObjectName("label_logo_upm")
        self.logos_h_layout.addWidget(self.label_logo_upm)
        self.label_logo_etsidi = QtWidgets.QLabel(self.h_start)
        self.label_logo_etsidi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo_etsidi.setObjectName("label_logo_etsidi")
        self.logos_h_layout.addWidget(self.label_logo_etsidi)
        
        logo_height = 150
        self.label_logo_upm.setPixmap(QtGui.QPixmap("logos/upm_logo_color.png").scaledToHeight(logo_height, mode=QtCore.Qt.SmoothTransformation))
        self.label_logo_etsidi.setPixmap(QtGui.QPixmap("logos/etsidi_color.png").scaledToHeight(round(logo_height*.8), mode=QtCore.Qt.SmoothTransformation))
    
        self.verticalLayout_13.addLayout(self.logos_h_layout)
        self.label_h_start = QtWidgets.QLabel(self.h_start)
        self.label_h_start.setObjectName("label_h_start")
        self.label_h_start.setWordWrap(True)
        self.verticalLayout_13.addWidget(self.label_h_start)
        self.help_toolBox.addItem(self.h_start, "")
        self.h_sim_w = QtWidgets.QWidget()
        self.h_sim_w.setGeometry(QtCore.QRect(0, 0, 747, 277))
        self.h_sim_w.setObjectName("h_sim_w")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.h_sim_w)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_h_sim_w = QtWidgets.QLabel(self.h_sim_w)
        self.label_h_sim_w.setObjectName("label_h_sim_w")
        self.label_h_sim_w.setWordWrap(True)
        self.horizontalLayout_11.addWidget(self.label_h_sim_w)
        self.help_toolBox.addItem(self.h_sim_w, "")

        self.h_motor = QtWidgets.QWidget()
        self.h_motor.setGeometry(QtCore.QRect(0, 0, 747, 277))
        self.h_motor.setObjectName("h_motor")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.h_motor)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_h_motor = QtWidgets.QLabel(self.h_motor)
        self.label_h_motor.setObjectName("label_h_motor")
        self.label_h_motor.setWordWrap(True)
        self.horizontalLayout_10.addWidget(self.label_h_motor)
        self.help_toolBox.addItem(self.h_motor, "")

        self.h_scale = QtWidgets.QWidget()
        self.h_scale.setGeometry(QtCore.QRect(0, 0, 747, 277))
        self.h_scale.setObjectName("h_scale")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.h_scale)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_h_scale = QtWidgets.QLabel(self.h_scale)
        self.label_h_scale.setObjectName("label_h_scale")
        self.label_h_scale.setWordWrap(True)
        self.horizontalLayout_12.addWidget(self.label_h_scale)
        self.help_toolBox.addItem(self.h_scale, "")

        self.h_settings = QtWidgets.QWidget()
        self.h_settings.setGeometry(QtCore.QRect(0, 0, 747, 277))
        self.h_settings.setObjectName("h_settings")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.h_settings)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_h_settings = QtWidgets.QLabel(self.h_settings)
        self.label_h_settings.setObjectName("label_h_settings")
        self.label_h_settings.setWordWrap(True)
        self.horizontalLayout_13.addWidget(self.label_h_settings)
        self.help_toolBox.addItem(self.h_settings, "")
        self.horizontalLayout_3.addWidget(self.help_toolBox)
        self.tabWidget.addTab(self.tab_help, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.help_toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MAFCE"))

        self.g_label_sim1.setText(_translate("MainWindow", "g"))
        self.g_label_sim2.setText(_translate("MainWindow", "g"))
        self.b_m50.setText(_translate("MainWindow", "-50 g"))
        self.b_m10.setText(_translate("MainWindow", "-10 g"))
        self.b_p10.setText(_translate("MainWindow", "+10 g"))
        self.b_m100.setText(_translate("MainWindow", "-100 g"))
        self.b_m500.setText(_translate("MainWindow", "-500 g"))
        self.b_m1000.setText(_translate("MainWindow", "-1000 g"))
        self.b_p50.setText(_translate("MainWindow", "+50 g"))
        self.b_p100.setText(_translate("MainWindow", "+100 g"))
        self.b_p500.setText(_translate("MainWindow", "+500 g"))
        self.b_p1000.setText(_translate("MainWindow", "+1000 g"))
        self.label_err_adm.setText(_translate("MainWindow", "Error admisible (g):"))
        self.label_err_act.setText(_translate("MainWindow", "Error actual (g):"))
        self.start_button.setText(_translate("MainWindow", "INICIAR"))
        self.b_sim2.setText(_translate("MainWindow", "2"))
        self.b_sim6.setText(_translate("MainWindow", "6"))
        self.b_sim1.setText(_translate("MainWindow", "1"))
        self.b_sim3.setText(_translate("MainWindow", "3"))
        self.b_sim7.setText(_translate("MainWindow", "7"))
        self.b_sim5.setText(_translate("MainWindow", "5"))
        self.b_sim4.setText(_translate("MainWindow", "4"))
        self.b_sim_del.setText(_translate("MainWindow", "\u232b"))
        self.b_sim8.setText(_translate("MainWindow", "8"))
        self.b_sim9.setText(_translate("MainWindow", "9"))
        self.b_sim0.setText(_translate("MainWindow", "0"))
        self.b_sim_enter.setText(_translate("MainWindow", "\u21b5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sim_w), _translate("MainWindow", "Simular Peso"))

        self.b_des_hold.setText(_translate("MainWindow", "Mantener pulsado para\n\nDESENROLLAR"))
        self.b_des_auto.setText(_translate("MainWindow", "DESENROLLAR\n\nautomáticamente"))
        self.g_label_mot.setText(_translate("MainWindow", "g"))
        self.b_enr_hold.setText(_translate("MainWindow", "Mantener pulsado para\n\nENROLLAR"))
        self.b_enr_auto.setText(_translate("MainWindow", "ENROLLAR\n\nautomáticamente"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_motor), _translate("MainWindow", "Motor"))
        
        self.g_label_sca.setText(_translate("MainWindow", "g"))
        self.label_sca_cel_w.setText(_translate("MainWindow", "Peso de la célula de carga (g):"))
        self.label_sca_colg_w.setText(_translate("MainWindow", "Peso colgado (g):"))
        self.b_sca_cal.setText(_translate("MainWindow", "Calibrar célula\nde carga"))
        self.b_sca_cel_w.setText(_translate("MainWindow", "Cambiar peso\nde la célula\nde carga"))
        self.b_sca_k.setText(_translate("MainWindow", "Estimar rigidez k\ndel sistema"))
        self.b_sca_canc.setText(_translate("MainWindow", "Cancelar"))
        self.b_sca_acep.setText(_translate("MainWindow", "Aceptar"))
        self.b_sca2.setText(_translate("MainWindow", "2"))
        self.b_sca6.setText(_translate("MainWindow", "6"))
        self.b_sca1.setText(_translate("MainWindow", "1"))
        self.b_sca3.setText(_translate("MainWindow", "3"))
        self.b_sca7.setText(_translate("MainWindow", "7"))
        self.b_sca5.setText(_translate("MainWindow", "5"))
        self.b_sca4.setText(_translate("MainWindow", "4"))
        self.b_sca_del.setText(_translate("MainWindow", "\u232b"))
        self.b_sca8.setText(_translate("MainWindow", "8"))
        self.b_sca9.setText(_translate("MainWindow", "9"))
        self.b_sca0.setText(_translate("MainWindow", "0"))
        self.b_sca_enter.setText(_translate("MainWindow", "\u21b5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_scale), _translate("MainWindow", "Báscula"))

        self.b_set2.setText(_translate("MainWindow", "2"))
        self.b_set8.setText(_translate("MainWindow", "8"))
        self.b_set6.setText(_translate("MainWindow", "6"))
        self.b_set1.setText(_translate("MainWindow", "1"))
        self.b_set7.setText(_translate("MainWindow", "7"))
        self.b_set5.setText(_translate("MainWindow", "5"))
        self.b_set9.setText(_translate("MainWindow", "9"))
        self.b_set0.setText(_translate("MainWindow", "0"))
        self.b_set3.setText(_translate("MainWindow", "3"))
        self.b_set_del.setText(_translate("MainWindow", "\u232b"))
        self.b_set_enter.setText(_translate("MainWindow", "\u21b5"))
        self.b_set4.setText(_translate("MainWindow", "4"))
        self.b_set_save.setText(_translate("MainWindow", "Guardar esta\nconfiguración"))
        self.b_set_apply.setText(_translate("MainWindow", "Aplicar cambios\nsolo a esta sesión"))
        self.b_set_reset.setText(_translate("MainWindow", "Restaurar valores\npor defecto"))
        self.b_set_undo.setText(_translate("MainWindow", "Deshacer cambios"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), _translate("MainWindow", "Ajustes"))

        self.label_h_start.setText(_translate("MainWindow", inicio))
        self.help_toolBox.setItemText(self.help_toolBox.indexOf(self.h_start), _translate("MainWindow", "Inicio"))
        self.label_h_sim_w.setText(_translate("MainWindow", sim_peso))
        self.help_toolBox.setItemText(self.help_toolBox.indexOf(self.h_sim_w), _translate("MainWindow", "Simular Peso"))
        self.label_h_motor.setText(_translate("MainWindow", motor))
        self.help_toolBox.setItemText(self.help_toolBox.indexOf(self.h_motor), _translate("MainWindow", "Motor"))
        self.label_h_scale.setText(_translate("MainWindow", bascula))
        self.help_toolBox.setItemText(self.help_toolBox.indexOf(self.h_scale), _translate("MainWindow", "Báscula"))
        self.label_h_settings.setText(_translate("MainWindow", ajustes))
        self.help_toolBox.setItemText(self.help_toolBox.indexOf(self.h_settings), _translate("MainWindow", "Ajustes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_help), _translate("MainWindow", "Ayuda"))


class main_window(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
    def closeEvent(self, event):
        close(ui)
        event.accept()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = main_window()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized()
    MainWindow.setCursor(QtCore.Qt.BlankCursor)  # No se muestra el cursor
    sys.exit(app.exec_())


